/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compilador;

import compilador.lexer.Lexer;
import compilador.lexer.LexerException;
import compilador.parser.ParserException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PushbackReader;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Affonso
 */
public class formPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form formPrincipal
     */
    public formPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        btnCarregarArquivo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextArea();
        txtLocalArquivo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRetorno = new javax.swing.JTextArea();
        btnAnalisarLexico = new javax.swing.JButton();
        btnAnaliseAST = new javax.swing.JButton();
        btnAnaliseCST = new javax.swing.JButton();
        lblLocalizacao = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnCarregarArquivo.setText("Abrir Arquivo");
        btnCarregarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarArquivoActionPerformed(evt);
            }
        });

        txtCodigo.setColumns(20);
        txtCodigo.setRows(5);
        txtCodigo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCodigoCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(txtCodigo);

        txtLocalArquivo.setEditable(false);
        txtLocalArquivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLocalArquivoMouseClicked(evt);
            }
        });

        txtRetorno.setEditable(false);
        txtRetorno.setColumns(20);
        txtRetorno.setLineWrap(true);
        txtRetorno.setRows(5);
        txtRetorno.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtRetorno);

        btnAnalisarLexico.setText("Analisar Léxico");
        btnAnalisarLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisarLexicoActionPerformed(evt);
            }
        });

        btnAnaliseAST.setText("Analisar AST");
        btnAnaliseAST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnaliseASTActionPerformed(evt);
            }
        });

        btnAnaliseCST.setText("Analisar CST");
        btnAnaliseCST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnaliseCSTActionPerformed(evt);
            }
        });

        lblLocalizacao.setText("1,1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnAnalisarLexico)
                        .addGap(48, 48, 48)
                        .addComponent(btnAnaliseCST)
                        .addGap(42, 42, 42)
                        .addComponent(btnAnaliseAST))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLocalizacao)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtLocalArquivo)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCarregarArquivo))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregarArquivo)
                    .addComponent(txtLocalArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLocalizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnalisarLexico)
                    .addComponent(btnAnaliseAST)
                    .addComponent(btnAnaliseCST))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarArquivoActionPerformed
        carregarArquivo();
    }//GEN-LAST:event_btnCarregarArquivoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (txtLocalArquivo.getText().isEmpty() && txtCodigo.getText().isEmpty()) {
            String filePath = new File("").getAbsolutePath();
            txtLocalArquivo.setText(filePath + "/src/compilador/teste.txt");
            try {
                txtCodigo.read(new FileReader(txtLocalArquivo.getText()), null);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(formPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(formPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtLocalArquivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLocalArquivoMouseClicked
        carregarArquivo();
    }//GEN-LAST:event_txtLocalArquivoMouseClicked

    private void btnAnalisarLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisarLexicoActionPerformed
        PushbackReader pushbackReader = new PushbackReader(new StringReader(txtCodigo.getText()));
        Lexico lex = new Lexico(pushbackReader);
        try {
            txtRetorno.setText(lex.Analisar());
        } catch (LexerException ex) {
            Logger.getLogger(formPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(formPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAnalisarLexicoActionPerformed

    private void btnAnaliseASTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnaliseASTActionPerformed
        PushbackReader pushbackReader = new PushbackReader(new StringReader(txtCodigo.getText()));
        Lexico lex = new Lexico(pushbackReader);
        Sintatico sint = new Sintatico(lex);
        try {
            txtRetorno.setText(sint.AnalisarAST());
        } catch (LexerException ex) {
            txtRetorno.setText(ex.getMessage());
            Logger.getLogger(formPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(formPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserException ex) {
            txtRetorno.setText(ex.getMessage().replace("expecting", "esperando"));
            Logger.getLogger(formPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAnaliseASTActionPerformed

    private void btnAnaliseCSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnaliseCSTActionPerformed
        PushbackReader pushbackReader = new PushbackReader(new StringReader(txtCodigo.getText()));
        Lexico lex = new Lexico(pushbackReader);
        Sintatico sint = new Sintatico(lex);
        try {
            txtRetorno.setText(sint.AnalisarCST());
        } catch (LexerException ex) {
            txtRetorno.setText(ex.getMessage());
            Logger.getLogger(formPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(formPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserException ex) {
            txtRetorno.setText(ex.getMessage().replace("expecting", "esperando"));
            Logger.getLogger(formPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAnaliseCSTActionPerformed

    private void txtCodigoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCodigoCaretUpdate
        int caretpos = 0;
        int linha = 1;
        int coluna = 1;
        try
        {
            caretpos = txtCodigo.getCaretPosition();
            linha = txtCodigo.getLineOfOffset(caretpos);
            coluna = caretpos - txtCodigo.getLineStartOffset(linha);
            coluna += 1;
            linha += 1;
        }
        catch(Exception ex) { }
        
        lblLocalizacao.setText(linha + "," + coluna);
    }//GEN-LAST:event_txtCodigoCaretUpdate

    private void carregarArquivo() {
        JFileChooser fileChooser = new JFileChooser();
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            txtLocalArquivo.setText(file.getAbsolutePath());
            try {
                txtCodigo.read(new FileReader(file.getAbsolutePath()), null);
            } catch (IOException ex) {
                System.out.println(ex);
            }
        } else {
            System.out.println("Cancelamento filechooser.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new formPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalisarLexico;
    private javax.swing.JButton btnAnaliseAST;
    private javax.swing.JButton btnAnaliseCST;
    private javax.swing.JButton btnCarregarArquivo;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLocalizacao;
    private javax.swing.JTextArea txtCodigo;
    private javax.swing.JTextField txtLocalArquivo;
    private javax.swing.JTextArea txtRetorno;
    // End of variables declaration//GEN-END:variables
}
