/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.lexer;

import java.io.*;
import compilador.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.NORMAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMENTARIO; break;
                                case 0: state = State.COMENTARIO; break;
                            }
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMENTARIO; break;
                            }
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            switch(state.id())
                            {
                                case 1: state = State.COMENTARIO; break;
                            }
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            @SuppressWarnings("hiding") Token token = new45(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            @SuppressWarnings("hiding") Token token = new46(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            @SuppressWarnings("hiding") Token token = new47(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            @SuppressWarnings("hiding") Token token = new48(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            @SuppressWarnings("hiding") Token token = new49(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            @SuppressWarnings("hiding") Token token = new50(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            @SuppressWarnings("hiding") Token token = new51(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            @SuppressWarnings("hiding") Token token = new52(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            @SuppressWarnings("hiding") Token token = new53(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            @SuppressWarnings("hiding") Token token = new54(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            @SuppressWarnings("hiding") Token token = new55(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentario(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioFim(line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioCorpo(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioLinha(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBranco(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrograma(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicio(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimPrograma(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoispontos(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontovirgula(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbrecolchete(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFechacolchete(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAbreparentese(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFechaparentese(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtribuicao(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConst(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInteiro(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TReal(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaractere(line, pos); }
    Token new20(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNInteiro(text, line, pos); }
    Token new21(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNReal(text, line, pos); }
    Token new22(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TString(text, line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAdicao(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSubtracao(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMultiplicacao(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDivisao(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TLeia(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEscreva(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSe(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEntao(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenao(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimse(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnquanto(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimenquanto(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFaca(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRepita(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDe(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAte(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAvalie(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimavalie(line, pos); }
    Token new41(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TCaso(line, pos); }
    Token new42(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPara(line, pos); }
    Token new43(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFimpara(line, pos); }
    Token new44(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPasso(line, pos); }
    Token new45(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TE(line, pos); }
    Token new46(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOu(line, pos); }
    Token new47(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TXor(line, pos); }
    Token new48(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgual(line, pos); }
    Token new49(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiferente(line, pos); }
    Token new50(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenor(line, pos); }
    Token new51(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaior(line, pos); }
    Token new52(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorigual(line, pos); }
    Token new53(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMaiorigual(line, pos); }
    Token new54(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNegacao(line, pos); }
    Token new55(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // NORMAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {39, 39, 5}, {40, 40, 6}, {41, 41, 7}, {42, 42, 8}, {43, 43, 9}, {44, 44, 10}, {45, 45, 11}, {47, 47, 12}, {48, 57, 13}, {58, 58, 14}, {59, 59, 15}, {60, 60, 16}, {61, 61, 17}, {62, 62, 18}, {65, 90, 19}, {91, 91, 20}, {93, 93, 21}, {95, 95, 22}, {97, 97, 23}, {98, 98, 19}, {99, 99, 24}, {100, 100, 25}, {101, 101, 26}, {102, 102, 27}, {103, 104, 19}, {105, 105, 28}, {106, 107, 19}, {108, 108, 29}, {109, 109, 19}, {110, 110, 30}, {111, 111, 31}, {112, 112, 32}, {113, 113, 19}, {114, 114, 33}, {115, 115, 34}, {116, 119, 19}, {120, 120, 35}, {121, 122, 19}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 9, 1}, {10, 10, 36}, {13, 32, -2}, },
            {{9, 32, -2}, },
            {{0, 9, 37}, {11, 12, 37}, {14, 38, 37}, {39, 39, 38}, {40, 127, 37}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {{42, 42, 39}, {47, 47, 40}, },
            {{46, 46, 41}, {48, 57, 13}, },
            {},
            {},
            {{45, 45, 42}, {61, 61, 43}, {62, 62, 44}, },
            {},
            {{61, 61, 45}, },
            {{48, 57, 46}, {65, 90, 47}, {95, 95, 48}, {97, 122, 47}, },
            {},
            {},
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 115, 47}, {116, 116, 49}, {117, 117, 47}, {118, 118, 50}, {119, 122, 47}, },
            {{48, 95, -21}, {97, 97, 51}, {98, 110, 47}, {111, 111, 52}, {112, 122, 47}, },
            {{48, 95, -21}, {97, 100, 47}, {101, 101, 53}, {102, 122, 47}, },
            {{48, 95, -21}, {97, 109, 47}, {110, 110, 54}, {111, 114, 47}, {115, 115, 55}, {116, 122, 47}, },
            {{48, 95, -21}, {97, 97, 56}, {98, 104, 47}, {105, 105, 57}, {106, 122, 47}, },
            {{48, 109, -28}, {110, 110, 58}, {111, 122, 47}, },
            {{48, 100, -27}, {101, 101, 59}, {102, 122, 47}, },
            {{48, 95, -21}, {97, 97, 60}, {98, 122, 47}, },
            {{48, 95, -21}, {97, 116, 47}, {117, 117, 61}, {118, 122, 47}, },
            {{48, 95, -21}, {97, 97, 62}, {98, 113, 47}, {114, 114, 63}, {115, 122, 47}, },
            {{48, 100, -27}, {101, 101, 64}, {102, 122, 47}, },
            {{48, 100, -27}, {101, 101, 65}, {102, 122, 47}, },
            {{48, 95, -21}, {97, 110, 47}, {111, 111, 66}, {112, 122, 47}, },
            {{9, 32, -2}, },
            {{0, 127, -7}, },
            {},
            {},
            {{0, 9, 67}, {10, 10, 68}, {11, 12, 67}, {13, 13, 69}, {14, 127, 67}, },
            {{48, 57, 70}, },
            {},
            {},
            {},
            {},
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 100, -27}, {101, 101, 71}, {102, 122, 47}, },
            {{48, 95, -21}, {97, 97, 72}, {98, 122, 47}, },
            {{48, 95, -21}, {97, 113, 47}, {114, 114, 73}, {115, 115, 74}, {116, 122, 47}, },
            {{48, 109, -28}, {110, 110, 75}, {111, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 112, 47}, {113, 113, 76}, {114, 115, 47}, {116, 116, 77}, {117, 122, 47}, },
            {{48, 95, -21}, {97, 98, 47}, {99, 99, 78}, {100, 122, 47}, },
            {{48, 98, -57}, {99, 99, 79}, {100, 122, 47}, },
            {{48, 95, -21}, {97, 108, 47}, {109, 109, 80}, {110, 122, 47}, },
            {{48, 95, -21}, {97, 104, 47}, {105, 105, 81}, {106, 115, 47}, {116, 116, 82}, {117, 122, 47}, },
            {{48, 104, -60}, {105, 105, 83}, {106, 122, 47}, },
            {{48, 110, -37}, {111, 111, 84}, {112, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 113, -53}, {114, 114, 85}, {115, 115, 86}, {116, 122, 47}, },
            {{48, 110, -37}, {111, 111, 87}, {112, 122, 47}, },
            {{48, 95, -21}, {97, 97, 88}, {98, 111, 47}, {112, 112, 89}, {113, 122, 47}, },
            {{48, 109, -28}, {110, 110, 90}, {111, 122, 47}, },
            {{48, 113, -53}, {114, 114, 91}, {115, 122, 47}, },
            {{0, 127, -42}, },
            {},
            {{10, 10, 92}, },
            {{48, 57, 70}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 107, 47}, {108, 108, 93}, {109, 122, 47}, },
            {{48, 95, -21}, {97, 97, 94}, {98, 122, 47}, },
            {{48, 110, -37}, {111, 111, 95}, {112, 122, 47}, },
            {{48, 95, -21}, {97, 114, 47}, {115, 115, 96}, {116, 122, 47}, },
            {{48, 116, -33}, {117, 117, 97}, {118, 122, 47}, },
            {{48, 95, -21}, {97, 97, 98}, {98, 122, 47}, },
            {{48, 113, -53}, {114, 114, 99}, {115, 122, 47}, },
            {{48, 95, -21}, {97, 97, 100}, {98, 122, 47}, },
            {{32, 32, 101}, {46, 46, 102}, {48, 122, -21}, },
            {{48, 98, -57}, {99, 99, 103}, {100, 122, 47}, },
            {{48, 100, -27}, {101, 101, 104}, {102, 122, 47}, },
            {{48, 95, -21}, {97, 97, 105}, {98, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 97, 106}, {98, 122, 47}, },
            {{48, 114, -77}, {115, 115, 107}, {116, 122, 47}, },
            {{48, 95, -21}, {97, 102, 47}, {103, 103, 108}, {104, 122, 47}, },
            {{48, 107, -74}, {108, 108, 109}, {109, 122, 47}, },
            {{48, 104, -60}, {105, 105, 110}, {106, 122, 47}, },
            {{48, 95, -21}, {97, 97, 111}, {98, 122, 47}, },
            {{48, 122, -21}, },
            {},
            {{48, 104, -60}, {105, 105, 112}, {106, 122, 47}, },
            {{48, 98, -57}, {99, 99, 113}, {100, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 115, -25}, {116, 116, 114}, {117, 122, 47}, },
            {{48, 95, -21}, {97, 97, 115}, {98, 122, 47}, },
            {{48, 110, -37}, {111, 111, 116}, {112, 122, 47}, },
            {{48, 100, -27}, {101, 101, 117}, {102, 122, 47}, },
            {{48, 122, -21}, },
            {{97, 97, 118}, {101, 101, 119}, {112, 112, 120}, {115, 115, 121}, },
            {},
            {{48, 104, -60}, {105, 105, 122}, {106, 122, 47}, },
            {{48, 104, -60}, {105, 105, 123}, {106, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 110, -37}, {111, 111, 124}, {112, 122, 47}, },
            {{48, 113, -53}, {114, 114, 125}, {115, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 115, -25}, {116, 116, 126}, {117, 122, 47}, },
            {{48, 110, -37}, {111, 111, 127}, {112, 122, 47}, },
            {{48, 100, -27}, {101, 101, 128}, {102, 122, 47}, },
            {{48, 115, -25}, {116, 116, 129}, {117, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 109, -28}, {110, 110, 130}, {111, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 117, 47}, {118, 118, 131}, {119, 122, 47}, },
            {{118, 118, 132}, },
            {{110, 110, 133}, },
            {{97, 97, 134}, },
            {{101, 101, 135}, },
            {{48, 110, -37}, {111, 111, 136}, {112, 122, 47}, },
            {{48, 113, -53}, {114, 114, 137}, {115, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 97, 138}, {98, 122, 47}, },
            {{48, 95, -21}, {97, 97, 139}, {98, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{48, 100, -27}, {101, 101, 140}, {102, 122, 47}, },
            {{48, 115, -25}, {116, 116, 141}, {117, 122, 47}, },
            {{48, 95, -21}, {97, 97, 142}, {98, 122, 47}, },
            {{97, 97, 143}, },
            {{113, 113, 144}, },
            {{114, 114, 145}, },
            {},
            {{48, 122, -21}, },
            {{48, 110, -37}, {111, 111, 146}, {112, 122, 47}, },
            {{48, 108, -59}, {109, 109, 147}, {110, 122, 47}, },
            {{48, 122, -21}, },
            {{48, 113, -53}, {114, 114, 148}, {115, 122, 47}, },
            {{48, 110, -37}, {111, 111, 149}, {112, 122, 47}, },
            {{48, 122, -21}, },
            {{108, 108, 150}, },
            {{117, 117, 151}, },
            {{97, 97, 152}, },
            {{48, 122, -21}, },
            {{48, 95, -21}, {97, 97, 153}, {98, 122, 47}, },
            {{48, 100, -27}, {101, 101, 154}, {102, 122, 47}, },
            {{48, 122, -21}, },
            {{105, 105, 155}, },
            {{97, 97, 156}, },
            {},
            {{48, 122, -21}, },
            {{48, 122, -21}, },
            {{101, 101, 157}, },
            {{110, 110, 158}, },
            {},
            {{116, 116, 159}, },
            {{111, 111, 160}, },
            {},
        }
        { // COMENTARIO
            {{0, 8, 1}, {9, 9, 2}, {10, 10, 3}, {11, 12, 1}, {13, 13, 4}, {14, 31, 1}, {32, 32, 5}, {33, 38, 1}, {39, 39, 6}, {40, 40, 7}, {41, 41, 8}, {42, 42, 9}, {43, 43, 10}, {44, 44, 11}, {45, 45, 12}, {46, 46, 1}, {47, 47, 13}, {48, 57, 14}, {58, 58, 15}, {59, 59, 16}, {60, 60, 17}, {61, 61, 18}, {62, 62, 19}, {63, 64, 1}, {65, 90, 20}, {91, 91, 21}, {92, 92, 1}, {93, 93, 22}, {94, 94, 1}, {95, 95, 23}, {96, 96, 1}, {97, 97, 24}, {98, 98, 20}, {99, 99, 25}, {100, 100, 26}, {101, 101, 27}, {102, 102, 28}, {103, 104, 20}, {105, 105, 29}, {106, 107, 20}, {108, 108, 30}, {109, 109, 20}, {110, 110, 31}, {111, 111, 32}, {112, 112, 33}, {113, 113, 20}, {114, 114, 34}, {115, 115, 35}, {116, 119, 20}, {120, 120, 36}, {121, 122, 20}, {123, 127, 1}, },
            {{0, 9, 1}, {10, 10, 37}, {11, 12, 1}, {13, 13, 38}, {14, 41, 1}, {43, 46, 1}, {48, 127, 1}, },
            {{0, 32, -2}, {33, 41, 1}, {43, 127, -3}, },
            {{0, 127, -4}, },
            {{0, 9, -2}, {10, 10, 39}, {11, 127, -4}, },
            {{0, 127, -4}, },
            {{0, 9, 40}, {10, 10, 37}, {11, 12, 40}, {13, 13, 38}, {14, 38, 40}, {39, 39, 41}, {40, 41, 40}, {42, 42, 42}, {43, 46, 40}, {47, 47, 42}, {48, 127, 40}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{47, 47, 43}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{42, 42, 44}, {47, 47, 45}, },
            {{0, 41, -3}, {43, 45, 1}, {46, 46, 46}, {48, 57, 14}, {58, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 41, -3}, {43, 44, 1}, {45, 45, 47}, {46, 46, 1}, {48, 60, 1}, {61, 61, 48}, {62, 62, 49}, {63, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 46, -3}, {48, 60, 1}, {61, 61, 50}, {62, 127, 1}, },
            {{0, 46, -3}, {48, 57, 51}, {58, 64, 1}, {65, 90, 52}, {91, 94, 1}, {95, 95, 53}, {96, 96, 1}, {97, 122, 52}, {123, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -22}, },
            {{0, 96, -22}, {97, 115, 52}, {116, 116, 54}, {117, 117, 52}, {118, 118, 55}, {119, 122, 52}, {123, 127, 1}, },
            {{0, 96, -22}, {97, 97, 56}, {98, 110, 52}, {111, 111, 57}, {112, 122, 52}, {123, 127, 1}, },
            {{0, 96, -22}, {97, 100, 52}, {101, 101, 58}, {102, 122, 52}, {123, 127, 1}, },
            {{0, 96, -22}, {97, 109, 52}, {110, 110, 59}, {111, 114, 52}, {115, 115, 60}, {116, 122, 52}, {123, 127, 1}, },
            {{0, 96, -22}, {97, 97, 61}, {98, 104, 52}, {105, 105, 62}, {106, 122, 52}, {123, 127, 1}, },
            {{0, 109, -29}, {110, 110, 63}, {111, 122, 52}, {123, 127, 1}, },
            {{0, 100, -28}, {101, 101, 64}, {102, 127, -28}, },
            {{0, 96, -22}, {97, 97, 65}, {98, 122, 52}, {123, 127, 1}, },
            {{0, 96, -22}, {97, 116, 52}, {117, 117, 66}, {118, 122, 52}, {123, 127, 1}, },
            {{0, 96, -22}, {97, 97, 67}, {98, 113, 52}, {114, 114, 68}, {115, 122, 52}, {123, 127, 1}, },
            {{0, 100, -28}, {101, 101, 69}, {102, 127, -28}, },
            {{0, 100, -28}, {101, 101, 70}, {102, 127, -28}, },
            {{0, 96, -22}, {97, 110, 52}, {111, 111, 71}, {112, 127, -27}, },
            {{0, 127, -3}, },
            {{0, 9, 1}, {10, 10, 72}, {11, 127, -3}, },
            {{0, 127, -4}, },
            {{0, 127, -8}, },
            {{0, 127, -3}, },
            {{0, 9, 42}, {11, 12, 42}, {14, 38, 42}, {39, 39, 73}, {40, 127, 42}, },
            {},
            {},
            {{0, 9, 74}, {10, 10, 75}, {11, 12, 74}, {13, 13, 76}, {14, 127, 74}, },
            {{0, 46, -3}, {48, 57, 77}, {58, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -3}, },
            {{0, 127, -22}, },
            {{0, 127, -22}, },
            {{0, 127, -22}, },
            {{0, 100, -28}, {101, 101, 78}, {102, 127, -28}, },
            {{0, 96, -22}, {97, 97, 79}, {98, 127, -33}, },
            {{0, 96, -22}, {97, 113, 52}, {114, 114, 80}, {115, 115, 81}, {116, 127, -29}, },
            {{0, 109, -29}, {110, 110, 82}, {111, 127, -31}, },
            {{0, 127, -22}, },
            {{0, 96, -22}, {97, 112, 52}, {113, 113, 83}, {114, 115, 52}, {116, 116, 84}, {117, 122, 52}, {123, 127, 1}, },
            {{0, 96, -22}, {97, 98, 52}, {99, 99, 85}, {100, 122, 52}, {123, 127, 1}, },
            {{0, 98, -62}, {99, 99, 86}, {100, 127, -62}, },
            {{0, 96, -22}, {97, 108, 52}, {109, 109, 87}, {110, 122, 52}, {123, 127, 1}, },
            {{0, 96, -22}, {97, 104, 52}, {105, 105, 88}, {106, 115, 52}, {116, 116, 89}, {117, 127, -61}, },
            {{0, 104, -65}, {105, 105, 90}, {106, 127, -30}, },
            {{0, 110, -38}, {111, 111, 91}, {112, 127, -27}, },
            {{0, 127, -22}, },
            {{0, 113, -58}, {114, 114, 92}, {115, 115, 93}, {116, 127, -29}, },
            {{0, 110, -38}, {111, 111, 94}, {112, 127, -27}, },
            {{0, 96, -22}, {97, 97, 95}, {98, 111, 52}, {112, 112, 96}, {113, 122, 52}, {123, 127, 1}, },
            {{0, 109, -29}, {110, 110, 97}, {111, 127, -31}, },
            {{0, 113, -58}, {114, 114, 98}, {115, 127, -35}, },
            {{0, 127, -3}, },
            {},
            {{0, 127, -47}, },
            {},
            {{10, 10, 99}, },
            {{0, 127, -48}, },
            {{0, 127, -22}, },
            {{0, 96, -22}, {97, 107, 52}, {108, 108, 100}, {109, 122, 52}, {123, 127, 1}, },
            {{0, 96, -22}, {97, 97, 101}, {98, 127, -33}, },
            {{0, 110, -38}, {111, 111, 102}, {112, 127, -27}, },
            {{0, 96, -22}, {97, 114, 52}, {115, 115, 103}, {116, 127, -29}, },
            {{0, 116, -34}, {117, 117, 104}, {118, 127, -34}, },
            {{0, 96, -22}, {97, 97, 105}, {98, 127, -33}, },
            {{0, 113, -58}, {114, 114, 106}, {115, 127, -35}, },
            {{0, 96, -22}, {97, 97, 107}, {98, 127, -33}, },
            {{0, 13, -3}, {14, 31, 1}, {32, 32, 108}, {33, 41, 1}, {43, 45, 1}, {46, 46, 109}, {48, 127, -22}, },
            {{0, 98, -62}, {99, 99, 110}, {100, 127, -62}, },
            {{0, 100, -28}, {101, 101, 111}, {102, 127, -28}, },
            {{0, 96, -22}, {97, 97, 112}, {98, 127, -33}, },
            {{0, 127, -22}, },
            {{0, 96, -22}, {97, 97, 113}, {98, 127, -33}, },
            {{0, 114, -84}, {115, 115, 114}, {116, 127, -29}, },
            {{0, 96, -22}, {97, 102, 52}, {103, 103, 115}, {104, 122, 52}, {123, 127, 1}, },
            {{0, 107, -81}, {108, 108, 116}, {109, 127, -81}, },
            {{0, 104, -65}, {105, 105, 117}, {106, 127, -30}, },
            {{0, 96, -22}, {97, 97, 118}, {98, 127, -33}, },
            {{0, 127, -22}, },
            {},
            {{0, 104, -65}, {105, 105, 119}, {106, 127, -30}, },
            {{0, 98, -62}, {99, 99, 120}, {100, 127, -62}, },
            {{0, 127, -22}, },
            {{0, 115, -26}, {116, 116, 121}, {117, 127, -61}, },
            {{0, 96, -22}, {97, 97, 122}, {98, 127, -33}, },
            {{0, 110, -38}, {111, 111, 123}, {112, 127, -27}, },
            {{0, 100, -28}, {101, 101, 124}, {102, 127, -28}, },
            {{0, 127, -22}, },
            {{0, 46, -3}, {48, 96, 1}, {97, 97, 125}, {98, 100, 1}, {101, 101, 126}, {102, 111, 1}, {112, 112, 127}, {113, 114, 1}, {115, 115, 128}, {116, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 104, -65}, {105, 105, 129}, {106, 127, -30}, },
            {{0, 104, -65}, {105, 105, 130}, {106, 127, -30}, },
            {{0, 127, -22}, },
            {{0, 127, -22}, },
            {{0, 110, -38}, {111, 111, 131}, {112, 127, -27}, },
            {{0, 113, -58}, {114, 114, 132}, {115, 127, -35}, },
            {{0, 127, -22}, },
            {{0, 115, -26}, {116, 116, 133}, {117, 127, -61}, },
            {{0, 110, -38}, {111, 111, 134}, {112, 127, -27}, },
            {{0, 100, -28}, {101, 101, 135}, {102, 127, -28}, },
            {{0, 115, -26}, {116, 116, 136}, {117, 127, -61}, },
            {{0, 127, -22}, },
            {{0, 109, -29}, {110, 110, 137}, {111, 127, -31}, },
            {{0, 127, -22}, },
            {{0, 96, -22}, {97, 117, 52}, {118, 118, 138}, {119, 127, -26}, },
            {{0, 46, -3}, {48, 117, 1}, {118, 118, 139}, {119, 127, 1}, },
            {{0, 46, -3}, {48, 109, 1}, {110, 110, 140}, {111, 127, 1}, },
            {{0, 96, -110}, {97, 97, 141}, {98, 127, 1}, },
            {{0, 46, -3}, {48, 100, 1}, {101, 101, 142}, {102, 127, 1}, },
            {{0, 110, -38}, {111, 111, 143}, {112, 127, -27}, },
            {{0, 113, -58}, {114, 114, 144}, {115, 127, -35}, },
            {{0, 127, -22}, },
            {{0, 96, -22}, {97, 97, 145}, {98, 127, -33}, },
            {{0, 96, -22}, {97, 97, 146}, {98, 127, -33}, },
            {{0, 127, -22}, },
            {{0, 127, -22}, },
            {{0, 100, -28}, {101, 101, 147}, {102, 127, -28}, },
            {{0, 115, -26}, {116, 116, 148}, {117, 127, -61}, },
            {{0, 96, -22}, {97, 97, 149}, {98, 127, -33}, },
            {{0, 96, -110}, {97, 97, 150}, {98, 127, 1}, },
            {{0, 46, -3}, {48, 112, 1}, {113, 113, 151}, {114, 127, 1}, },
            {{0, 46, -3}, {48, 113, 1}, {114, 114, 152}, {115, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -22}, },
            {{0, 110, -38}, {111, 111, 153}, {112, 127, -27}, },
            {{0, 108, -64}, {109, 109, 154}, {110, 127, -64}, },
            {{0, 127, -22}, },
            {{0, 113, -58}, {114, 114, 155}, {115, 127, -35}, },
            {{0, 110, -38}, {111, 111, 156}, {112, 127, -27}, },
            {{0, 127, -22}, },
            {{0, 46, -3}, {48, 107, 1}, {108, 108, 157}, {109, 127, 1}, },
            {{0, 46, -3}, {48, 116, 1}, {117, 117, 158}, {118, 127, 1}, },
            {{0, 96, -110}, {97, 97, 159}, {98, 127, 1}, },
            {{0, 127, -22}, },
            {{0, 96, -22}, {97, 97, 160}, {98, 127, -33}, },
            {{0, 100, -28}, {101, 101, 161}, {102, 127, -28}, },
            {{0, 127, -22}, },
            {{0, 46, -3}, {48, 104, 1}, {105, 105, 162}, {106, 127, 1}, },
            {{0, 96, -110}, {97, 97, 163}, {98, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 127, -22}, },
            {{0, 127, -22}, },
            {{0, 100, -130}, {101, 101, 164}, {102, 127, 1}, },
            {{0, 109, -128}, {110, 110, 165}, {111, 127, 1}, },
            {{0, 127, -3}, },
            {{0, 46, -3}, {48, 115, 1}, {116, 116, 166}, {117, 127, 1}, },
            {{0, 46, -3}, {48, 110, 1}, {111, 111, 167}, {112, 127, 1}, },
            {{0, 127, -3}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // NORMAL
        {-1, 4, 4, 4, 4, -1, 13, 14, 25, 23, 9, 24, 26, 20, 8, 10, 50, 48, 51, 55, 11, 12, 55, 55, 55, 55, 45, 55, 55, 55, 55, 55, 55, 55, 55, 55, 4, -1, 22, 0, 3, -1, 15, 52, 49, 53, 55, 55, 55, 55, 55, 55, 55, 37, 55, 55, 55, 55, 55, 55, 55, 46, 55, 55, 55, 29, 55, 3, 3, 3, 21, 38, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 54, 55, 55, 55, 55, 55, 55, 47, 3, 55, 55, 41, 55, 55, 55, 55, 35, -1, 7, 55, 55, 27, 42, 55, 55, 18, 55, 55, 55, 55, 16, 55, 30, 55, -1, -1, -1, -1, 55, 55, 44, 55, 55, 31, 39, 55, 55, 55, -1, -1, -1, 32, 6, 55, 55, 36, 55, 55, 28, -1, -1, -1, 17, 55, 55, 33, -1, -1, 43, 5, 19, -1, -1, 40, -1, -1, 34, },
        // COMENTARIO
        {2, 2, 2, 2, 2, 2, 2, 2, 2, 25, 2, 2, 2, 26, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, -1, 1, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 22, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, },

    };*/

    public static class State
    {
        public final static State NORMAL = new State(0);
        public final static State COMENTARIO = new State(1);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
