/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ACasoValorCasoValorLista extends PCasoValorLista
{
    private PCasoValor _casoValor_;

    public ACasoValorCasoValorLista()
    {
        // Constructor
    }

    public ACasoValorCasoValorLista(
        @SuppressWarnings("hiding") PCasoValor _casoValor_)
    {
        // Constructor
        setCasoValor(_casoValor_);

    }

    @Override
    public Object clone()
    {
        return new ACasoValorCasoValorLista(
            cloneNode(this._casoValor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACasoValorCasoValorLista(this);
    }

    public PCasoValor getCasoValor()
    {
        return this._casoValor_;
    }

    public void setCasoValor(PCasoValor node)
    {
        if(this._casoValor_ != null)
        {
            this._casoValor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._casoValor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._casoValor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._casoValor_ == child)
        {
            this._casoValor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._casoValor_ == oldChild)
        {
            setCasoValor((PCasoValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
