/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ACasoCasoValorOp extends PCasoValorOp
{
    private PCasoValorLista _casoValorLista_;

    public ACasoCasoValorOp()
    {
        // Constructor
    }

    public ACasoCasoValorOp(
        @SuppressWarnings("hiding") PCasoValorLista _casoValorLista_)
    {
        // Constructor
        setCasoValorLista(_casoValorLista_);

    }

    @Override
    public Object clone()
    {
        return new ACasoCasoValorOp(
            cloneNode(this._casoValorLista_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACasoCasoValorOp(this);
    }

    public PCasoValorLista getCasoValorLista()
    {
        return this._casoValorLista_;
    }

    public void setCasoValorLista(PCasoValorLista node)
    {
        if(this._casoValorLista_ != null)
        {
            this._casoValorLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._casoValorLista_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._casoValorLista_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._casoValorLista_ == child)
        {
            this._casoValorLista_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._casoValorLista_ == oldChild)
        {
            setCasoValorLista((PCasoValorLista) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
