/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ACasoValorListaCasoValorLista extends PCasoValorLista
{
    private PCasoValorLista _casoValorLista_;
    private PCasoValor _casoValor_;

    public ACasoValorListaCasoValorLista()
    {
        // Constructor
    }

    public ACasoValorListaCasoValorLista(
        @SuppressWarnings("hiding") PCasoValorLista _casoValorLista_,
        @SuppressWarnings("hiding") PCasoValor _casoValor_)
    {
        // Constructor
        setCasoValorLista(_casoValorLista_);

        setCasoValor(_casoValor_);

    }

    @Override
    public Object clone()
    {
        return new ACasoValorListaCasoValorLista(
            cloneNode(this._casoValorLista_),
            cloneNode(this._casoValor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACasoValorListaCasoValorLista(this);
    }

    public PCasoValorLista getCasoValorLista()
    {
        return this._casoValorLista_;
    }

    public void setCasoValorLista(PCasoValorLista node)
    {
        if(this._casoValorLista_ != null)
        {
            this._casoValorLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._casoValorLista_ = node;
    }

    public PCasoValor getCasoValor()
    {
        return this._casoValor_;
    }

    public void setCasoValor(PCasoValor node)
    {
        if(this._casoValor_ != null)
        {
            this._casoValor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._casoValor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._casoValorLista_)
            + toString(this._casoValor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._casoValorLista_ == child)
        {
            this._casoValorLista_ = null;
            return;
        }

        if(this._casoValor_ == child)
        {
            this._casoValor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._casoValorLista_ == oldChild)
        {
            setCasoValorLista((PCasoValorLista) newChild);
            return;
        }

        if(this._casoValor_ == oldChild)
        {
            setCasoValor((PCasoValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
