/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AComListaComandoLista extends PComandoLista
{
    private PComandoLista _comandoLista_;
    private PComando _comando_;

    public AComListaComandoLista()
    {
        // Constructor
    }

    public AComListaComandoLista(
        @SuppressWarnings("hiding") PComandoLista _comandoLista_,
        @SuppressWarnings("hiding") PComando _comando_)
    {
        // Constructor
        setComandoLista(_comandoLista_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new AComListaComandoLista(
            cloneNode(this._comandoLista_),
            cloneNode(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComListaComandoLista(this);
    }

    public PComandoLista getComandoLista()
    {
        return this._comandoLista_;
    }

    public void setComandoLista(PComandoLista node)
    {
        if(this._comandoLista_ != null)
        {
            this._comandoLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoLista_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoLista_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoLista_ == child)
        {
            this._comandoLista_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoLista_ == oldChild)
        {
            setComandoLista((PComandoLista) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
