/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AEnquantoComando extends PComando
{
    private TEnquanto _enquanto_;
    private TAbreparentese _abreparentese_;
    private PExpLogicaLista _expLogicaLista_;
    private TFechaparentese _fechaparentese_;
    private TFaca _faca_;
    private PComandoOpLista _comandoOpLista_;
    private TFimenquanto _fimenquanto_;
    private TPontovirgula _pontovirgula_;

    public AEnquantoComando()
    {
        // Constructor
    }

    public AEnquantoComando(
        @SuppressWarnings("hiding") TEnquanto _enquanto_,
        @SuppressWarnings("hiding") TAbreparentese _abreparentese_,
        @SuppressWarnings("hiding") PExpLogicaLista _expLogicaLista_,
        @SuppressWarnings("hiding") TFechaparentese _fechaparentese_,
        @SuppressWarnings("hiding") TFaca _faca_,
        @SuppressWarnings("hiding") PComandoOpLista _comandoOpLista_,
        @SuppressWarnings("hiding") TFimenquanto _fimenquanto_,
        @SuppressWarnings("hiding") TPontovirgula _pontovirgula_)
    {
        // Constructor
        setEnquanto(_enquanto_);

        setAbreparentese(_abreparentese_);

        setExpLogicaLista(_expLogicaLista_);

        setFechaparentese(_fechaparentese_);

        setFaca(_faca_);

        setComandoOpLista(_comandoOpLista_);

        setFimenquanto(_fimenquanto_);

        setPontovirgula(_pontovirgula_);

    }

    @Override
    public Object clone()
    {
        return new AEnquantoComando(
            cloneNode(this._enquanto_),
            cloneNode(this._abreparentese_),
            cloneNode(this._expLogicaLista_),
            cloneNode(this._fechaparentese_),
            cloneNode(this._faca_),
            cloneNode(this._comandoOpLista_),
            cloneNode(this._fimenquanto_),
            cloneNode(this._pontovirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnquantoComando(this);
    }

    public TEnquanto getEnquanto()
    {
        return this._enquanto_;
    }

    public void setEnquanto(TEnquanto node)
    {
        if(this._enquanto_ != null)
        {
            this._enquanto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._enquanto_ = node;
    }

    public TAbreparentese getAbreparentese()
    {
        return this._abreparentese_;
    }

    public void setAbreparentese(TAbreparentese node)
    {
        if(this._abreparentese_ != null)
        {
            this._abreparentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abreparentese_ = node;
    }

    public PExpLogicaLista getExpLogicaLista()
    {
        return this._expLogicaLista_;
    }

    public void setExpLogicaLista(PExpLogicaLista node)
    {
        if(this._expLogicaLista_ != null)
        {
            this._expLogicaLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaLista_ = node;
    }

    public TFechaparentese getFechaparentese()
    {
        return this._fechaparentese_;
    }

    public void setFechaparentese(TFechaparentese node)
    {
        if(this._fechaparentese_ != null)
        {
            this._fechaparentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaparentese_ = node;
    }

    public TFaca getFaca()
    {
        return this._faca_;
    }

    public void setFaca(TFaca node)
    {
        if(this._faca_ != null)
        {
            this._faca_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._faca_ = node;
    }

    public PComandoOpLista getComandoOpLista()
    {
        return this._comandoOpLista_;
    }

    public void setComandoOpLista(PComandoOpLista node)
    {
        if(this._comandoOpLista_ != null)
        {
            this._comandoOpLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoOpLista_ = node;
    }

    public TFimenquanto getFimenquanto()
    {
        return this._fimenquanto_;
    }

    public void setFimenquanto(TFimenquanto node)
    {
        if(this._fimenquanto_ != null)
        {
            this._fimenquanto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fimenquanto_ = node;
    }

    public TPontovirgula getPontovirgula()
    {
        return this._pontovirgula_;
    }

    public void setPontovirgula(TPontovirgula node)
    {
        if(this._pontovirgula_ != null)
        {
            this._pontovirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontovirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._enquanto_)
            + toString(this._abreparentese_)
            + toString(this._expLogicaLista_)
            + toString(this._fechaparentese_)
            + toString(this._faca_)
            + toString(this._comandoOpLista_)
            + toString(this._fimenquanto_)
            + toString(this._pontovirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._enquanto_ == child)
        {
            this._enquanto_ = null;
            return;
        }

        if(this._abreparentese_ == child)
        {
            this._abreparentese_ = null;
            return;
        }

        if(this._expLogicaLista_ == child)
        {
            this._expLogicaLista_ = null;
            return;
        }

        if(this._fechaparentese_ == child)
        {
            this._fechaparentese_ = null;
            return;
        }

        if(this._faca_ == child)
        {
            this._faca_ = null;
            return;
        }

        if(this._comandoOpLista_ == child)
        {
            this._comandoOpLista_ = null;
            return;
        }

        if(this._fimenquanto_ == child)
        {
            this._fimenquanto_ = null;
            return;
        }

        if(this._pontovirgula_ == child)
        {
            this._pontovirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._enquanto_ == oldChild)
        {
            setEnquanto((TEnquanto) newChild);
            return;
        }

        if(this._abreparentese_ == oldChild)
        {
            setAbreparentese((TAbreparentese) newChild);
            return;
        }

        if(this._expLogicaLista_ == oldChild)
        {
            setExpLogicaLista((PExpLogicaLista) newChild);
            return;
        }

        if(this._fechaparentese_ == oldChild)
        {
            setFechaparentese((TFechaparentese) newChild);
            return;
        }

        if(this._faca_ == oldChild)
        {
            setFaca((TFaca) newChild);
            return;
        }

        if(this._comandoOpLista_ == oldChild)
        {
            setComandoOpLista((PComandoOpLista) newChild);
            return;
        }

        if(this._fimenquanto_ == oldChild)
        {
            setFimenquanto((TFimenquanto) newChild);
            return;
        }

        if(this._pontovirgula_ == oldChild)
        {
            setPontovirgula((TPontovirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
