/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import java.util.*;
import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AEscrevaComando extends PComando
{
    private final LinkedList<PExpressao> _expressao_ = new LinkedList<PExpressao>();

    public AEscrevaComando()
    {
        // Constructor
    }

    public AEscrevaComando(
        @SuppressWarnings("hiding") List<?> _expressao_)
    {
        // Constructor
        setExpressao(_expressao_);

    }

    @Override
    public Object clone()
    {
        return new AEscrevaComando(
            cloneList(this._expressao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEscrevaComando(this);
    }

    public LinkedList<PExpressao> getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(List<?> list)
    {
        for(PExpressao e : this._expressao_)
        {
            e.parent(null);
        }
        this._expressao_.clear();

        for(Object obj_e : list)
        {
            PExpressao e = (PExpressao) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._expressao_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressao_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PExpressao> i = this._expressao_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpressao) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
