/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AListaComandoOp extends PComandoOp
{
    private PComandoLista _comandoLista_;

    public AListaComandoOp()
    {
        // Constructor
    }

    public AListaComandoOp(
        @SuppressWarnings("hiding") PComandoLista _comandoLista_)
    {
        // Constructor
        setComandoLista(_comandoLista_);

    }

    @Override
    public Object clone()
    {
        return new AListaComandoOp(
            cloneNode(this._comandoLista_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaComandoOp(this);
    }

    public PComandoLista getComandoLista()
    {
        return this._comandoLista_;
    }

    public void setComandoLista(PComandoLista node)
    {
        if(this._comandoLista_ != null)
        {
            this._comandoLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoLista_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoLista_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoLista_ == child)
        {
            this._comandoLista_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoLista_ == oldChild)
        {
            setComandoLista((PComandoLista) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
