/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AListaVarVirgulaOp extends PVarVirgulaOp
{
    private PVarVirgulaLista _varVirgulaLista_;

    public AListaVarVirgulaOp()
    {
        // Constructor
    }

    public AListaVarVirgulaOp(
        @SuppressWarnings("hiding") PVarVirgulaLista _varVirgulaLista_)
    {
        // Constructor
        setVarVirgulaLista(_varVirgulaLista_);

    }

    @Override
    public Object clone()
    {
        return new AListaVarVirgulaOp(
            cloneNode(this._varVirgulaLista_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaVarVirgulaOp(this);
    }

    public PVarVirgulaLista getVarVirgulaLista()
    {
        return this._varVirgulaLista_;
    }

    public void setVarVirgulaLista(PVarVirgulaLista node)
    {
        if(this._varVirgulaLista_ != null)
        {
            this._varVirgulaLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varVirgulaLista_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varVirgulaLista_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varVirgulaLista_ == child)
        {
            this._varVirgulaLista_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varVirgulaLista_ == oldChild)
        {
            setVarVirgulaLista((PVarVirgulaLista) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
