/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ALogicoExpLogica extends PExpLogica
{
    private PExpLogicaOriginal _expLogicaOriginal_;
    private PLogicoEouxor _logicoEouxor_;

    public ALogicoExpLogica()
    {
        // Constructor
    }

    public ALogicoExpLogica(
        @SuppressWarnings("hiding") PExpLogicaOriginal _expLogicaOriginal_,
        @SuppressWarnings("hiding") PLogicoEouxor _logicoEouxor_)
    {
        // Constructor
        setExpLogicaOriginal(_expLogicaOriginal_);

        setLogicoEouxor(_logicoEouxor_);

    }

    @Override
    public Object clone()
    {
        return new ALogicoExpLogica(
            cloneNode(this._expLogicaOriginal_),
            cloneNode(this._logicoEouxor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogicoExpLogica(this);
    }

    public PExpLogicaOriginal getExpLogicaOriginal()
    {
        return this._expLogicaOriginal_;
    }

    public void setExpLogicaOriginal(PExpLogicaOriginal node)
    {
        if(this._expLogicaOriginal_ != null)
        {
            this._expLogicaOriginal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaOriginal_ = node;
    }

    public PLogicoEouxor getLogicoEouxor()
    {
        return this._logicoEouxor_;
    }

    public void setLogicoEouxor(PLogicoEouxor node)
    {
        if(this._logicoEouxor_ != null)
        {
            this._logicoEouxor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicoEouxor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogicaOriginal_)
            + toString(this._logicoEouxor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogicaOriginal_ == child)
        {
            this._expLogicaOriginal_ = null;
            return;
        }

        if(this._logicoEouxor_ == child)
        {
            this._logicoEouxor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogicaOriginal_ == oldChild)
        {
            setExpLogicaOriginal((PExpLogicaOriginal) newChild);
            return;
        }

        if(this._logicoEouxor_ == oldChild)
        {
            setLogicoEouxor((PLogicoEouxor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
