/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ANRealValor extends PValor
{
    private TNReal _nReal_;

    public ANRealValor()
    {
        // Constructor
    }

    public ANRealValor(
        @SuppressWarnings("hiding") TNReal _nReal_)
    {
        // Constructor
        setNReal(_nReal_);

    }

    @Override
    public Object clone()
    {
        return new ANRealValor(
            cloneNode(this._nReal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANRealValor(this);
    }

    public TNReal getNReal()
    {
        return this._nReal_;
    }

    public void setNReal(TNReal node)
    {
        if(this._nReal_ != null)
        {
            this._nReal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nReal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nReal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nReal_ == child)
        {
            this._nReal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nReal_ == oldChild)
        {
            setNReal((TNReal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
