/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AParaComando extends PComando
{
    private PParaInicio _paraInicio_;
    private PParaFim _paraFim_;

    public AParaComando()
    {
        // Constructor
    }

    public AParaComando(
        @SuppressWarnings("hiding") PParaInicio _paraInicio_,
        @SuppressWarnings("hiding") PParaFim _paraFim_)
    {
        // Constructor
        setParaInicio(_paraInicio_);

        setParaFim(_paraFim_);

    }

    @Override
    public Object clone()
    {
        return new AParaComando(
            cloneNode(this._paraInicio_),
            cloneNode(this._paraFim_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParaComando(this);
    }

    public PParaInicio getParaInicio()
    {
        return this._paraInicio_;
    }

    public void setParaInicio(PParaInicio node)
    {
        if(this._paraInicio_ != null)
        {
            this._paraInicio_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paraInicio_ = node;
    }

    public PParaFim getParaFim()
    {
        return this._paraFim_;
    }

    public void setParaFim(PParaFim node)
    {
        if(this._paraFim_ != null)
        {
            this._paraFim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paraFim_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._paraInicio_)
            + toString(this._paraFim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._paraInicio_ == child)
        {
            this._paraInicio_ = null;
            return;
        }

        if(this._paraFim_ == child)
        {
            this._paraFim_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._paraInicio_ == oldChild)
        {
            setParaInicio((PParaInicio) newChild);
            return;
        }

        if(this._paraFim_ == oldChild)
        {
            setParaFim((PParaFim) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
