/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ARelacionalExpLogica extends PExpLogica
{
    private PExpLogicaOriginal _expLogicaOriginal_;

    public ARelacionalExpLogica()
    {
        // Constructor
    }

    public ARelacionalExpLogica(
        @SuppressWarnings("hiding") PExpLogicaOriginal _expLogicaOriginal_)
    {
        // Constructor
        setExpLogicaOriginal(_expLogicaOriginal_);

    }

    @Override
    public Object clone()
    {
        return new ARelacionalExpLogica(
            cloneNode(this._expLogicaOriginal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelacionalExpLogica(this);
    }

    public PExpLogicaOriginal getExpLogicaOriginal()
    {
        return this._expLogicaOriginal_;
    }

    public void setExpLogicaOriginal(PExpLogicaOriginal node)
    {
        if(this._expLogicaOriginal_ != null)
        {
            this._expLogicaOriginal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogicaOriginal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expLogicaOriginal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expLogicaOriginal_ == child)
        {
            this._expLogicaOriginal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expLogicaOriginal_ == oldChild)
        {
            setExpLogicaOriginal((PExpLogicaOriginal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
