/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ASenaoSenaoDoispontosOp extends PSenaoDoispontosOp
{
    private PSenaoDoispontos _senaoDoispontos_;

    public ASenaoSenaoDoispontosOp()
    {
        // Constructor
    }

    public ASenaoSenaoDoispontosOp(
        @SuppressWarnings("hiding") PSenaoDoispontos _senaoDoispontos_)
    {
        // Constructor
        setSenaoDoispontos(_senaoDoispontos_);

    }

    @Override
    public Object clone()
    {
        return new ASenaoSenaoDoispontosOp(
            cloneNode(this._senaoDoispontos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASenaoSenaoDoispontosOp(this);
    }

    public PSenaoDoispontos getSenaoDoispontos()
    {
        return this._senaoDoispontos_;
    }

    public void setSenaoDoispontos(PSenaoDoispontos node)
    {
        if(this._senaoDoispontos_ != null)
        {
            this._senaoDoispontos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senaoDoispontos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._senaoDoispontos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._senaoDoispontos_ == child)
        {
            this._senaoDoispontos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._senaoDoispontos_ == oldChild)
        {
            setSenaoDoispontos((PSenaoDoispontos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
