/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ASenaoSenaoOp extends PSenaoOp
{
    private PSenaoComando _senaoComando_;

    public ASenaoSenaoOp()
    {
        // Constructor
    }

    public ASenaoSenaoOp(
        @SuppressWarnings("hiding") PSenaoComando _senaoComando_)
    {
        // Constructor
        setSenaoComando(_senaoComando_);

    }

    @Override
    public Object clone()
    {
        return new ASenaoSenaoOp(
            cloneNode(this._senaoComando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASenaoSenaoOp(this);
    }

    public PSenaoComando getSenaoComando()
    {
        return this._senaoComando_;
    }

    public void setSenaoComando(PSenaoComando node)
    {
        if(this._senaoComando_ != null)
        {
            this._senaoComando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senaoComando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._senaoComando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._senaoComando_ == child)
        {
            this._senaoComando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._senaoComando_ == oldChild)
        {
            setSenaoComando((PSenaoComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
