/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ASomaSomaExp extends PSomaExp
{
    private PSomaExp _somaExp_;
    private PSoma _soma_;
    private PTermo _termo_;

    public ASomaSomaExp()
    {
        // Constructor
    }

    public ASomaSomaExp(
        @SuppressWarnings("hiding") PSomaExp _somaExp_,
        @SuppressWarnings("hiding") PSoma _soma_,
        @SuppressWarnings("hiding") PTermo _termo_)
    {
        // Constructor
        setSomaExp(_somaExp_);

        setSoma(_soma_);

        setTermo(_termo_);

    }

    @Override
    public Object clone()
    {
        return new ASomaSomaExp(
            cloneNode(this._somaExp_),
            cloneNode(this._soma_),
            cloneNode(this._termo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomaSomaExp(this);
    }

    public PSomaExp getSomaExp()
    {
        return this._somaExp_;
    }

    public void setSomaExp(PSomaExp node)
    {
        if(this._somaExp_ != null)
        {
            this._somaExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._somaExp_ = node;
    }

    public PSoma getSoma()
    {
        return this._soma_;
    }

    public void setSoma(PSoma node)
    {
        if(this._soma_ != null)
        {
            this._soma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._soma_ = node;
    }

    public PTermo getTermo()
    {
        return this._termo_;
    }

    public void setTermo(PTermo node)
    {
        if(this._termo_ != null)
        {
            this._termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._somaExp_)
            + toString(this._soma_)
            + toString(this._termo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._somaExp_ == child)
        {
            this._somaExp_ = null;
            return;
        }

        if(this._soma_ == child)
        {
            this._soma_ = null;
            return;
        }

        if(this._termo_ == child)
        {
            this._termo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._somaExp_ == oldChild)
        {
            setSomaExp((PSomaExp) newChild);
            return;
        }

        if(this._soma_ == oldChild)
        {
            setSoma((PSoma) newChild);
            return;
        }

        if(this._termo_ == oldChild)
        {
            setTermo((PTermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
