/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AVarVirgulaVarVirgulaLista extends PVarVirgulaLista
{
    private PVarVirgula _varVirgula_;

    public AVarVirgulaVarVirgulaLista()
    {
        // Constructor
    }

    public AVarVirgulaVarVirgulaLista(
        @SuppressWarnings("hiding") PVarVirgula _varVirgula_)
    {
        // Constructor
        setVarVirgula(_varVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AVarVirgulaVarVirgulaLista(
            cloneNode(this._varVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarVirgulaVarVirgulaLista(this);
    }

    public PVarVirgula getVarVirgula()
    {
        return this._varVirgula_;
    }

    public void setVarVirgula(PVarVirgula node)
    {
        if(this._varVirgula_ != null)
        {
            this._varVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varVirgula_ == child)
        {
            this._varVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varVirgula_ == oldChild)
        {
            setVarVirgula((PVarVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
