/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AVetorVar extends PVar
{
    private TId _id_;
    private TAbrecolchete _abrecolchete_;
    private TNInteiro _nInteiro_;
    private TFechacolchete _fechacolchete_;

    public AVetorVar()
    {
        // Constructor
    }

    public AVetorVar(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TAbrecolchete _abrecolchete_,
        @SuppressWarnings("hiding") TNInteiro _nInteiro_,
        @SuppressWarnings("hiding") TFechacolchete _fechacolchete_)
    {
        // Constructor
        setId(_id_);

        setAbrecolchete(_abrecolchete_);

        setNInteiro(_nInteiro_);

        setFechacolchete(_fechacolchete_);

    }

    @Override
    public Object clone()
    {
        return new AVetorVar(
            cloneNode(this._id_),
            cloneNode(this._abrecolchete_),
            cloneNode(this._nInteiro_),
            cloneNode(this._fechacolchete_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVetorVar(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TAbrecolchete getAbrecolchete()
    {
        return this._abrecolchete_;
    }

    public void setAbrecolchete(TAbrecolchete node)
    {
        if(this._abrecolchete_ != null)
        {
            this._abrecolchete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abrecolchete_ = node;
    }

    public TNInteiro getNInteiro()
    {
        return this._nInteiro_;
    }

    public void setNInteiro(TNInteiro node)
    {
        if(this._nInteiro_ != null)
        {
            this._nInteiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nInteiro_ = node;
    }

    public TFechacolchete getFechacolchete()
    {
        return this._fechacolchete_;
    }

    public void setFechacolchete(TFechacolchete node)
    {
        if(this._fechacolchete_ != null)
        {
            this._fechacolchete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechacolchete_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._abrecolchete_)
            + toString(this._nInteiro_)
            + toString(this._fechacolchete_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._abrecolchete_ == child)
        {
            this._abrecolchete_ = null;
            return;
        }

        if(this._nInteiro_ == child)
        {
            this._nInteiro_ = null;
            return;
        }

        if(this._fechacolchete_ == child)
        {
            this._fechacolchete_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._abrecolchete_ == oldChild)
        {
            setAbrecolchete((TAbrecolchete) newChild);
            return;
        }

        if(this._nInteiro_ == oldChild)
        {
            setNInteiro((TNInteiro) newChild);
            return;
        }

        if(this._fechacolchete_ == oldChild)
        {
            setFechacolchete((TFechacolchete) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
