/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AVirgulaExpVirgulaOp extends PExpVirgulaOp
{
    private PExpViruglaLista _expViruglaLista_;

    public AVirgulaExpVirgulaOp()
    {
        // Constructor
    }

    public AVirgulaExpVirgulaOp(
        @SuppressWarnings("hiding") PExpViruglaLista _expViruglaLista_)
    {
        // Constructor
        setExpViruglaLista(_expViruglaLista_);

    }

    @Override
    public Object clone()
    {
        return new AVirgulaExpVirgulaOp(
            cloneNode(this._expViruglaLista_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVirgulaExpVirgulaOp(this);
    }

    public PExpViruglaLista getExpViruglaLista()
    {
        return this._expViruglaLista_;
    }

    public void setExpViruglaLista(PExpViruglaLista node)
    {
        if(this._expViruglaLista_ != null)
        {
            this._expViruglaLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expViruglaLista_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expViruglaLista_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expViruglaLista_ == child)
        {
            this._expViruglaLista_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expViruglaLista_ == oldChild)
        {
            setExpViruglaLista((PExpViruglaLista) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
