/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AVirgulaListaVarVirgulaLista extends PVarVirgulaLista
{
    private PVarVirgulaLista _varVirgulaLista_;
    private PVarVirgula _varVirgula_;

    public AVirgulaListaVarVirgulaLista()
    {
        // Constructor
    }

    public AVirgulaListaVarVirgulaLista(
        @SuppressWarnings("hiding") PVarVirgulaLista _varVirgulaLista_,
        @SuppressWarnings("hiding") PVarVirgula _varVirgula_)
    {
        // Constructor
        setVarVirgulaLista(_varVirgulaLista_);

        setVarVirgula(_varVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AVirgulaListaVarVirgulaLista(
            cloneNode(this._varVirgulaLista_),
            cloneNode(this._varVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVirgulaListaVarVirgulaLista(this);
    }

    public PVarVirgulaLista getVarVirgulaLista()
    {
        return this._varVirgulaLista_;
    }

    public void setVarVirgulaLista(PVarVirgulaLista node)
    {
        if(this._varVirgulaLista_ != null)
        {
            this._varVirgulaLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varVirgulaLista_ = node;
    }

    public PVarVirgula getVarVirgula()
    {
        return this._varVirgula_;
    }

    public void setVarVirgula(PVarVirgula node)
    {
        if(this._varVirgula_ != null)
        {
            this._varVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varVirgulaLista_)
            + toString(this._varVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varVirgulaLista_ == child)
        {
            this._varVirgulaLista_ = null;
            return;
        }

        if(this._varVirgula_ == child)
        {
            this._varVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varVirgulaLista_ == oldChild)
        {
            setVarVirgulaLista((PVarVirgulaLista) newChild);
            return;
        }

        if(this._varVirgula_ == oldChild)
        {
            setVarVirgula((PVarVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
